width: 1440
height: 1080
Offset_x: 0
Offset_y: 0
FrameRateEnable: false
FrameRate: 100.0
BurstFrameCount: 1
ExposureMode: 0
ExposureTime: 5000
GammaEnable: true
Gamma: 0.7
GainAuto: 2
Gain: 15.0
SaturationEnable: false
Saturation: 128
BalanceWhiteMode: 0
BalanceRatio_Red: 1400
BalanceRatio_Green: 1000
BalanceRatio_Blue: 2000
TriggerMode: 1
TriggerSource: 99
LineSelector: 99